# Generated by Django 3.2.3 on 2021-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phno', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('lisence', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
