# Generated by Django 3.2.3 on 2021-06-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_auto_20210621_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datedemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currdate', models.DateTimeField()),
            ],
        ),
    ]
