# Generated by Django 3.2.3 on 2021-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_datedemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Datedemo',
        ),
    ]
