# Generated by Django 3.2.3 on 2021-06-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to='uploadfiles/'),
        ),
    ]
