# Generated by Django 3.2.3 on 2021-06-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_alter_documents_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='file',
        ),
    ]
