# Generated by Django 3.2.3 on 2021-06-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_remove_documents_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
