# Generated by Django 3.2.3 on 2021-06-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
