# Generated by Django 3.2.3 on 2021-07-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(max_length=25)),
            ],
        ),
    ]
